import { useEffect, useState, useCallback, useRef } from 'react'
import type { DashboardStats, Config, OperationResult, Alert, LogEntry, Threat, MLModelStatus, MLPrediction, EntropyStats } from '../types'

// Wails runtime types - these will be generated by Wails
declare global {
  interface Window {
    go: {
      gui: {
        App: {
          StartProtection: () => Promise<OperationResult>
          StopProtection: () => Promise<OperationResult>
          IsProtecting: () => Promise<boolean>
          GetDashboardStats: () => Promise<DashboardStats>
          GetConfiguration: () => Promise<Config>
          SaveConfiguration: (config: Config) => Promise<OperationResult>
          GetLogs: (limit: number) => Promise<LogEntry[]>
          ClearLogs: () => Promise<void>
          StartLogStream: () => Promise<void>
          StopLogStream: () => Promise<void>
          GetActiveThreats: () => Promise<Threat[]>
          GetEntropyStats: () => Promise<EntropyStats>
          LoadMLModel: (filePath: string) => Promise<OperationResult>
          UnloadMLModel: () => Promise<OperationResult>
          GetMLModelStatus: () => Promise<MLModelStatus>
          SetMLDetectionEnabled: (enabled: boolean) => Promise<OperationResult>
          SetMLConfidenceThreshold: (threshold: number) => Promise<OperationResult>
          SelectMLModelFile: () => Promise<string>
        }
      }
    }
    runtime: {
      EventsOn: (eventName: string, callback: (data: unknown) => void) => () => void
      EventsOff: (eventName: string) => void
    }
  }
}

// Default stats for when protection is not running
const defaultStats: DashboardStats = {
  protectionStatus: 'Stopped',
  etwConnected: false,
  workerQueueDepth: 0,
  alertsProcessed: 0,
  processesTerminated: 0,
  filesQuarantined: 0,
  canaryFilesCount: 0,
  activeThreatsCount: 0,
  autoResponsesBlocked: 0,
  highIOProcessCount: 0,
  etwDiagnostics: {
    eventsReceived: 0,
    eventsDropped: 0,
    eventsSuppressedDeadPID: 0,
    workerPoolSize: 0,
    channelCapacity: 0,
    channelLength: 0,
  },
  entropyStats: {
    trackedFiles: 0,
    modifiedFiles: 0,
    significantIncreases: 0,
  },
}

export function useProtection() {
  const [isProtecting, setIsProtecting] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const checkStatus = useCallback(async () => {
    try {
      if (window.go?.gui?.App?.IsProtecting) {
        const status = await window.go.gui.App.IsProtecting()
        setIsProtecting(status)
      }
    } catch (err) {
      console.error('Failed to check protection status:', err)
    }
  }, [])

  useEffect(() => {
    checkStatus()
  }, [checkStatus])

  const startProtection = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      if (window.go?.gui?.App?.StartProtection) {
        const result = await window.go.gui.App.StartProtection()
        if (result.success) {
          setIsProtecting(true)
        } else {
          setError(result.message)
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to start protection')
    } finally {
      setLoading(false)
    }
  }, [])

  const stopProtection = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      if (window.go?.gui?.App?.StopProtection) {
        const result = await window.go.gui.App.StopProtection()
        if (result.success) {
          setIsProtecting(false)
        } else {
          setError(result.message)
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to stop protection')
    } finally {
      setLoading(false)
    }
  }, [])

  return { isProtecting, loading, error, startProtection, stopProtection }
}

export function useDashboardStats() {
  const [stats, setStats] = useState<DashboardStats>(defaultStats)

  useEffect(() => {
    // Initial fetch
    const fetchStats = async () => {
      try {
        if (window.go?.gui?.App?.GetDashboardStats) {
          const data = await window.go.gui.App.GetDashboardStats()
          setStats(data)
        }
      } catch (err) {
        console.error('Failed to fetch stats:', err)
      }
    }

    fetchStats()

    // Subscribe to stats updates
    let unsubscribe: (() => void) | undefined
    if (window.runtime?.EventsOn) {
      unsubscribe = window.runtime.EventsOn('stats:update', (data) => {
        setStats(data as DashboardStats)
      })
    }

    return () => {
      if (unsubscribe) unsubscribe()
    }
  }, [])

  return stats
}

export function useAlerts() {
  const [alerts, setAlerts] = useState<Alert[]>([])

  useEffect(() => {
    let unsubscribe: (() => void) | undefined
    if (window.runtime?.EventsOn) {
      unsubscribe = window.runtime.EventsOn('alert:new', (data) => {
        setAlerts((prev) => [data as Alert, ...prev].slice(0, 100))
      })
    }

    return () => {
      if (unsubscribe) unsubscribe()
    }
  }, [])

  return alerts
}

export function useThreats() {
  const [threats, setThreats] = useState<Threat[]>([])

  useEffect(() => {
    const fetchThreats = async () => {
      try {
        if (window.go?.gui?.App?.GetActiveThreats) {
          const data = await window.go.gui.App.GetActiveThreats()
          setThreats(data || [])
        }
      } catch (err) {
        console.error('Failed to fetch threats:', err)
      }
    }

    fetchThreats()

    let unsubscribe: (() => void) | undefined
    if (window.runtime?.EventsOn) {
      unsubscribe = window.runtime.EventsOn('threat:update', (data) => {
        setThreats((data as Threat[]) || [])
      })
    }

    return () => {
      if (unsubscribe) unsubscribe()
    }
  }, [])

  return threats
}

export function useMLModel() {
  const [status, setStatus] = useState<MLModelStatus>({
    loaded: false,
    filePath: '',
    modelName: '',
    modelType: '',
    loadedAt: '',
    enabled: false,
    featureCount: 0,
    confidenceThreshold: 0.75,
  })
  const [loading, setLoading] = useState(false)
  const [predictions, setPredictions] = useState<MLPrediction[]>([])

  const fetchStatus = useCallback(async () => {
    try {
      if (window.go?.gui?.App?.GetMLModelStatus) {
        const data = await window.go.gui.App.GetMLModelStatus()
        setStatus(data)
      }
    } catch (err) {
      console.error('Failed to fetch ML model status:', err)
    }
  }, [])

  useEffect(() => {
    fetchStatus()
  }, [fetchStatus])

  // Subscribe to real-time ML prediction events
  useEffect(() => {
    const unsub = (window as any).runtime?.EventsOn?.('ml:prediction', (pred: MLPrediction) => {
      setPredictions(prev => [pred, ...prev].slice(0, 100)) // keep last 100
    })
    return () => { unsub?.() }
  }, [])

  const selectAndLoadModel = useCallback(async () => {
    setLoading(true)
    try {
      if (window.go?.gui?.App?.SelectMLModelFile) {
        const filePath = await window.go.gui.App.SelectMLModelFile()
        if (filePath) {
          const result = await window.go.gui.App.LoadMLModel(filePath)
          if (result.success) {
            await fetchStatus()
          }
          return result
        }
        return { success: false, message: 'No file selected' }
      }
      return { success: false, message: 'Wails not initialized' }
    } finally {
      setLoading(false)
    }
  }, [fetchStatus])

  const unloadModel = useCallback(async () => {
    if (window.go?.gui?.App?.UnloadMLModel) {
      const result = await window.go.gui.App.UnloadMLModel()
      if (result.success) await fetchStatus()
      return result
    }
    return { success: false, message: 'Wails not initialized' }
  }, [fetchStatus])

  const setEnabled = useCallback(async (enabled: boolean) => {
    if (window.go?.gui?.App?.SetMLDetectionEnabled) {
      const result = await window.go.gui.App.SetMLDetectionEnabled(enabled)
      if (result.success) await fetchStatus()
      return result
    }
    return { success: false, message: 'Wails not initialized' }
  }, [fetchStatus])

  const setThreshold = useCallback(async (threshold: number) => {
    if (window.go?.gui?.App?.SetMLConfidenceThreshold) {
      const result = await window.go.gui.App.SetMLConfidenceThreshold(threshold)
      if (result.success) await fetchStatus()
      return result
    }
    return { success: false, message: 'Wails not initialized' }
  }, [fetchStatus])

  return { status, loading, predictions, selectAndLoadModel, unloadModel, setEnabled, setThreshold }
}

export function useConfiguration() {
  const [config, setConfig] = useState<Config | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const loadConfig = useCallback(async () => {
    setLoading(true)
    try {
      if (window.go?.gui?.App?.GetConfiguration) {
        const data = await window.go.gui.App.GetConfiguration()
        setConfig(data)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load configuration')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    loadConfig()
  }, [loadConfig])

  const saveConfig = useCallback(async (newConfig: Config) => {
    setSaving(true)
    setError(null)
    try {
      if (window.go?.gui?.App?.SaveConfiguration) {
        const result = await window.go.gui.App.SaveConfiguration(newConfig)
        if (result.success) {
          setConfig(newConfig)
        } else {
          setError(result.message)
        }
        return result
      }
      return { success: false, message: 'Wails not initialized' }
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to save configuration'
      setError(message)
      return { success: false, message }
    } finally {
      setSaving(false)
    }
  }, [])

  return { config, loading, saving, error, saveConfig, reload: loadConfig }
}

export function useLogs(maxEntries: number = 200) {
  const [logs, setLogs] = useState<LogEntry[]>([])
  const [autoScroll, setAutoScroll] = useState(true)
  const logsRef = useRef<LogEntry[]>([])

  // Load initial logs
  useEffect(() => {
    const loadLogs = async () => {
      try {
        if (window.go?.gui?.App?.GetLogs) {
          const data = await window.go.gui.App.GetLogs(maxEntries)
          setLogs(data)
          logsRef.current = data
        }
      } catch (err) {
        console.error('Failed to load logs:', err)
      }
    }

    loadLogs()

    // Start log streaming
    if (window.go?.gui?.App?.StartLogStream) {
      window.go.gui.App.StartLogStream()
    }

    // Subscribe to log entries
    let unsubscribe: (() => void) | undefined
    if (window.runtime?.EventsOn) {
      unsubscribe = window.runtime.EventsOn('log:entry', (data) => {
        const entry = data as LogEntry
        logsRef.current = [...logsRef.current, entry].slice(-maxEntries)
        setLogs([...logsRef.current])
      })
    }

    return () => {
      if (unsubscribe) unsubscribe()
      if (window.go?.gui?.App?.StopLogStream) {
        window.go.gui.App.StopLogStream()
      }
    }
  }, [maxEntries])

  const clearLogs = useCallback(async () => {
    try {
      if (window.go?.gui?.App?.ClearLogs) {
        await window.go.gui.App.ClearLogs()
        setLogs([])
        logsRef.current = []
      }
    } catch (err) {
      console.error('Failed to clear logs:', err)
    }
  }, [])

  return { logs, clearLogs, autoScroll, setAutoScroll }
}
