// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {logger} from '../models';

export function ClearLogs():Promise<void>;

export function GetConfiguration():Promise<models.ConfigViewModel>;

export function GetDashboardStats():Promise<models.DashboardStats>;

export function GetLogs(arg1:number):Promise<Array<logger.LogEntry>>;

export function IsProtecting():Promise<boolean>;

export function SaveConfiguration(arg1:models.ConfigViewModel):Promise<models.OperationResult>;

export function StartLogStream():Promise<void>;

export function StartProtection():Promise<models.OperationResult>;

export function StopLogStream():Promise<void>;

export function StopProtection():Promise<models.OperationResult>;
