// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['gui']['App']['ClearLogs']();
}

export function GetConfiguration() {
  return window['go']['gui']['App']['GetConfiguration']();
}

export function GetDashboardStats() {
  return window['go']['gui']['App']['GetDashboardStats']();
}

export function GetLogs(arg1) {
  return window['go']['gui']['App']['GetLogs'](arg1);
}

export function IsProtecting() {
  return window['go']['gui']['App']['IsProtecting']();
}

export function SaveConfiguration(arg1) {
  return window['go']['gui']['App']['SaveConfiguration'](arg1);
}

export function StartLogStream() {
  return window['go']['gui']['App']['StartLogStream']();
}

export function StartProtection() {
  return window['go']['gui']['App']['StartProtection']();
}

export function StopLogStream() {
  return window['go']['gui']['App']['StopLogStream']();
}

export function StopProtection() {
  return window['go']['gui']['App']['StopProtection']();
}
