// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['gui']['App']['ClearLogs']();
}

export function GetActiveThreats() {
  return window['go']['gui']['App']['GetActiveThreats']();
}

export function GetCanaryResponseAction() {
  return window['go']['gui']['App']['GetCanaryResponseAction']();
}

export function GetConfiguration() {
  return window['go']['gui']['App']['GetConfiguration']();
}

export function GetDashboardStats() {
  return window['go']['gui']['App']['GetDashboardStats']();
}

export function GetDetectionMode() {
  return window['go']['gui']['App']['GetDetectionMode']();
}

export function GetEntropyStats() {
  return window['go']['gui']['App']['GetEntropyStats']();
}

export function GetLogs(arg1) {
  return window['go']['gui']['App']['GetLogs'](arg1);
}

export function GetMLModelStatus() {
  return window['go']['gui']['App']['GetMLModelStatus']();
}

export function IsProtecting() {
  return window['go']['gui']['App']['IsProtecting']();
}

export function LoadMLModel(arg1) {
  return window['go']['gui']['App']['LoadMLModel'](arg1);
}

export function SaveConfiguration(arg1) {
  return window['go']['gui']['App']['SaveConfiguration'](arg1);
}

export function SelectMLModelFile() {
  return window['go']['gui']['App']['SelectMLModelFile']();
}

export function SetCanaryResponseAction(arg1) {
  return window['go']['gui']['App']['SetCanaryResponseAction'](arg1);
}

export function SetDetectionMode(arg1) {
  return window['go']['gui']['App']['SetDetectionMode'](arg1);
}

export function SetMLConfidenceThreshold(arg1) {
  return window['go']['gui']['App']['SetMLConfidenceThreshold'](arg1);
}

export function SetMLDetectionEnabled(arg1) {
  return window['go']['gui']['App']['SetMLDetectionEnabled'](arg1);
}

export function StartLogStream() {
  return window['go']['gui']['App']['StartLogStream']();
}

export function StartProtection() {
  return window['go']['gui']['App']['StartProtection']();
}

export function StopLogStream() {
  return window['go']['gui']['App']['StopLogStream']();
}

export function StopProtection() {
  return window['go']['gui']['App']['StopProtection']();
}

export function UnloadMLModel() {
  return window['go']['gui']['App']['UnloadMLModel']();
}
